// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/ent/eventmap"
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventMapDelete is the builder for deleting a EventMap entity.
type EventMapDelete struct {
	config
	hooks    []Hook
	mutation *EventMapMutation
}

// Where appends a list predicates to the EventMapDelete builder.
func (emd *EventMapDelete) Where(ps ...predicate.EventMap) *EventMapDelete {
	emd.mutation.Where(ps...)
	return emd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (emd *EventMapDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, EventMapMutation](ctx, emd.sqlExec, emd.mutation, emd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (emd *EventMapDelete) ExecX(ctx context.Context) int {
	n, err := emd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (emd *EventMapDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: eventmap.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: eventmap.FieldID,
			},
		},
	}
	if ps := emd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, emd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	emd.mutation.done = true
	return affected, err
}

// EventMapDeleteOne is the builder for deleting a single EventMap entity.
type EventMapDeleteOne struct {
	emd *EventMapDelete
}

// Exec executes the deletion query.
func (emdo *EventMapDeleteOne) Exec(ctx context.Context) error {
	n, err := emdo.emd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventmap.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (emdo *EventMapDeleteOne) ExecX(ctx context.Context) {
	emdo.emd.ExecX(ctx)
}
