export default function Head() {
	return (
		<>
			<title>MapIt</title>
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />
			<meta
				name="viewport"
				content="width=device-width, initial-scale=1 user-scalable=no"
			/>
			<link rel="icon" href="/favicon.ico" />
		</>
	);
}
