import Head from "next/head";
import Header from "../components/Header";

export default function Page() {
	return (
		<div>
			<Head>
				<title>MapIt</title>
				<meta content="width=device-width, initial-scale=1" name="viewport" />
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="border-b-gray-400 border-b">
				<Header />
			</div>

			<div className="flex flex-col justify-centerk items-center pt-4">
				<div className="text-2xl">Welcome!</div>
				<div>
					This section is still under construction but feel free to create an
					account and take a look around.
				</div>
			</div>
		</div>
	);
}
