import Head from "next/head";
import Header from "../components/Header";
import dynamic from "next/dynamic";

export const HeaderHeight = 90;
export const FooterHeight = 60;
// corresponds to the 'lg' breakpoint defined by tailwindcss
export const MobileLayoutBreakpoint = 1024;

export default function Page() {
	const ResponsiveEventMapWithNoSSR = dynamic(
		() => import("../components/ResponsiveEventMap"),
		{
			ssr: false,
		},
	);

	return (
		<div>
			<Head>
				<title>MapIt</title>
				<meta content="width=device-width, initial-scale=1" name="viewport" />
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				className="grid"
				style={{
					height: "100dvh",
					gridTemplateRows: `${HeaderHeight}px auto ${FooterHeight}px`,
				}}
			>
				<Header />
				<ResponsiveEventMapWithNoSSR />
			</div>
		</div>
	);
}
