import dynamic from "next/dynamic";
import Head from "next/head";
import Header from "../components/Header";

export default function Page() {
	const MapWithNoSSR = dynamic(() => import("../components/Map"), {
		ssr: false,
	});

	return (
		<div>
			<Head>
				<title>MapIt</title>
				<meta content="width=device-width, initial-scale=1" name="viewport" />
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				className="grid"
				style={{
					height: "100vh",
					gridTemplateRows: "90px auto",
				}}
			>
				<Header />

				<MapWithNoSSR />
			</div>
		</div>
	);
}
