// Code generated by ent, DO NOT EDIT.

package eventmap

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the eventmap type in the database.
	Label = "event_map"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBoundingBox holds the string denoting the bounding_box field in the database.
	FieldBoundingBox = "bounding_box"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the eventmap in the database.
	Table = "event_maps"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "event_map_events"
)

// Columns holds all SQL columns for eventmap fields.
var Columns = []string{
	FieldID,
	FieldOwnerID,
	FieldName,
	FieldBoundingBox,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
